# Generated by Django 2.2.16 on 2020-11-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_post_published_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Usuario',
        ),
    ]
