# Generated by Django 2.2.16 on 2020-11-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20201118_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='domicilio',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='nacimiento',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
