# Generated by Django 2.2.16 on 2020-11-19 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_auto_20201118_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('dni', models.IntegerField(default=None)),
                ('domicilio', models.CharField(max_length=200)),
                ('nacimiento', models.DateField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
